// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Alexandria, Nothing_You_Could_Do} from "next/font/google";

const alexandria = Alexandria({
  subsets: ["latin"],
  weight: ["400", "700"], 
});

// Font for specific elements
const nothingYouCouldDo = Nothing_You_Could_Do({
  subsets: ["latin"],
  weight: ["400"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// export const metadata = {
//   title: "My App",
//   description: "Testing fonts in Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alexandria.className}>{children}</body>
    </html>
  );
}
